export * from './consentRequests.service';
import { ConsentRequestsService } from './consentRequests.service';
export * from './dataProducts.service';
import { DataProductsService } from './dataProducts.service';
export * from './dataRequests.service';
import { DataRequestsService } from './dataRequests.service';
export * from './dataTransfer.service';
import { DataTransferService } from './dataTransfer.service';
export * from './infoResource.service';
import { InfoResourceService } from './infoResource.service';
export * from './participants.service';
import { ParticipantsService } from './participants.service';
export * from './testData.service';
import { TestDataService } from './testData.service';
export * from './uIDRegisterSearch.service';
import { UIDRegisterSearchService } from './uIDRegisterSearch.service';
export const APIS = [ConsentRequestsService, DataProductsService, DataRequestsService, DataTransferService, InfoResourceService, ParticipantsService, TestDataService, UIDRegisterSearchService];
