export * from './agisTestController.service';
import { AgisTestControllerService } from './agisTestController.service';
export * from './consentRequests.service';
import { ConsentRequestsService } from './consentRequests.service';
export * from './dataProducts.service';
import { DataProductsService } from './dataProducts.service';
export * from './dataRequests.service';
import { DataRequestsService } from './dataRequests.service';
export * from './infoResource.service';
import { InfoResourceService } from './infoResource.service';
export * from './testData.service';
import { TestDataService } from './testData.service';
export * from './uidRegisterSearch.service';
import { UidRegisterSearchService } from './uidRegisterSearch.service';
export const APIS = [AgisTestControllerService, ConsentRequestsService, DataProductsService, DataRequestsService, InfoResourceService, TestDataService, UidRegisterSearchService];
