/**
 * backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestState } from './consentRequestState';
import { DataRequest } from './dataRequest';


export interface ConsentRequest { 
    id?: string;
    dataProducerUid?: string;
    state?: ConsentRequestState;
    requestDate?: string;
    dataRequest?: DataRequest;
}
export namespace ConsentRequest {
}


