/**
 * backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DataRequestState = {
    Granted: 'GRANTED',
    Opened: 'OPENED',
    Declined: 'DECLINED'
} as const;
export type DataRequestState = typeof DataRequestState[keyof typeof DataRequestState];

