/**
 * backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataRequest { 
    id?: string;
    descriptionDe?: string;
    descriptionFr?: string;
    descriptionIt?: string;
    purposeDe?: string;
    purposeFr?: string;
    purposeIt?: string;
    dataConsumerBur?: string;
}

