/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestStateEnum } from './consentRequestStateEnum';
import { ConsentRequestDtoDataRequest } from './consentRequestDtoDataRequest';


/**
 * Data transfer object representing a consent request
 */
export interface ConsentRequestDto { 
    id?: string;
    /**
     * Unique identifier of the data producer
     */
    dataProducerUid?: string;
    /**
     * Current state of the consent request
     */
    state?: ConsentRequestStateEnum;
    requestDate?: string;
    dataRequest?: ConsentRequestDtoDataRequest;
}
export namespace ConsentRequestDto {
}


