/**
 * backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const ConsentRequestState = {
  Granted: 'GRANTED',
  Opened: 'OPENED',
  Declined: 'DECLINED',
} as const;
export type ConsentRequestState = (typeof ConsentRequestState)[keyof typeof ConsentRequestState];
