/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestDtoDataRequestDataConsumer } from './consentRequestDtoDataRequestDataConsumer';


/**
 * Details of the underlying data request
 */
export interface ConsentRequestDtoDataRequest { 
    id: string;
    /**
     * Title of the data request in German
     */
    titleDe?: string;
    /**
     * Title of the data request in French
     */
    titleFr?: string;
    /**
     * Title of the data request in Italian
     */
    titleIt?: string;
    /**
     * Description of the data request in German
     */
    descriptionDe?: string;
    /**
     * Description of the data request in French
     */
    descriptionFr?: string;
    /**
     * Description of the data request in Italian
     */
    descriptionIt?: string;
    /**
     * Purpose of the data request in German
     */
    purposeDe?: string;
    /**
     * Purpose of the data request in French
     */
    purposeFr?: string;
    /**
     * Purpose of the data request in Italian
     */
    purposeIt?: string;
    dataConsumer?: ConsentRequestDtoDataRequestDataConsumer;
}

