/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ConsentRequestStateEnum = {
    Granted: 'GRANTED',
    Opened: 'OPENED',
    Declined: 'DECLINED'
} as const;
export type ConsentRequestStateEnum = typeof ConsentRequestStateEnum[keyof typeof ConsentRequestStateEnum];

