/**
 * backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const DataRequestStateDto = {
  Granted: 'GRANTED',
  Opened: 'OPENED',
  Declined: 'DECLINED',
} as const;
export type DataRequestStateDto = (typeof DataRequestStateDto)[keyof typeof DataRequestStateDto];
