/**
 * backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestStateDto } from './dataRequestState';

export interface DataRequestDto {
  requestDate?: string;
  descriptionDe?: string;
  descriptionFr?: string;
  descriptionIt?: string;
  dataConsumer?: string;
  state?: DataRequestStateDto;
}
export namespace DataRequestDto {}
