/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgbTextDto } from './agbTextDto';


/**
 * Data transfer object representing an agb revision
 */
export interface AgbRevisionDto { 
    id?: string;
    /**
     * Version of the data request
     */
    version?: string;
    validFrom?: string;
    /**
     * Data transfer object representing an agb text
     */
    agbText?: AgbTextDto;
}

