/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisFarmPersonDetailsType } from './agisFarmPersonDetailsType';
import { AgisStructuralDataRootType } from './agisStructuralDataRootType';


export interface AgisStructuralDataType { 
    ktIdB: string;
    ber?: string;
    ktIdP: string;
    uid?: string;
    farmPersonDetails: AgisFarmPersonDetailsType;
    structuralDataRoot?: AgisStructuralDataRootType;
}

