/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisAquaticAnimalPerCategory } from './agisAquaticAnimalPerCategory';


export interface AgisAquaticAnimalTypes { 
    aquaticAnimalPerCategory: Array<AgisAquaticAnimalPerCategory>;
}

