/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisSelfReportedDataType } from './agisSelfReportedDataType';
import { AgisAtdDataType } from './agisAtdDataType';


export interface AgisAnimalStock { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    animalCategory: string;
    atdData?: AgisAtdDataType;
    selfreportedData?: Array<AgisSelfReportedDataType>;
    BTSRAUS?: number;
}

