/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisFarmCharacteristicsType } from './agisFarmCharacteristicsType';
import { AgisPersonDetailsType } from './agisPersonDetailsType';
import { AgisFarmDetailsType } from './agisFarmDetailsType';


export interface AgisFarmPersonDetailsType { 
    farmDetails: AgisFarmDetailsType;
    personDetails: AgisPersonDetailsType;
    farmCharacteristics: AgisFarmCharacteristicsType;
}

