/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisAddressInformationType { 
    addressLine1?: string;
    addressLine3?: string;
    street?: string;
    houseNumber?: string;
    town?: string;
    swissZipCode?: number;
    foreignZipCode?: string;
}

