/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisNetworkContribution } from './agisNetworkContribution';


export interface AgisNetworkSurface { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    cultureId?: string;
    locality?: string;
    municipalityId?: number;
    agriculturalZone?: string;
    cultivationType: string;
    cultivationTypeAttribute?: string;
    areaGross?: number;
    areaNet: number;
    networkCommitmentStart?: number;
    networkContribution?: Array<AgisNetworkContribution>;
    contributionAuthorization?: boolean;
}

