/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AgisCantonFlAbbreviationType = {
    Zh: 'ZH',
    Be: 'BE',
    Lu: 'LU',
    Ur: 'UR',
    Sz: 'SZ',
    Ow: 'OW',
    Nw: 'NW',
    Gl: 'GL',
    Zg: 'ZG',
    Fr: 'FR',
    So: 'SO',
    Bs: 'BS',
    Bl: 'BL',
    Sh: 'SH',
    Ar: 'AR',
    Ai: 'AI',
    Sg: 'SG',
    Gr: 'GR',
    Ag: 'AG',
    Tg: 'TG',
    Ti: 'TI',
    Vd: 'VD',
    Vs: 'VS',
    Ne: 'NE',
    Ge: 'GE',
    Ju: 'JU',
    Fl: 'FL'
} as const;
export type AgisCantonFlAbbreviationType = typeof AgisCantonFlAbbreviationType[keyof typeof AgisCantonFlAbbreviationType];

