/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisFarmGeneralDataDeclaration } from './agisFarmGeneralDataDeclaration';
import { AgisFarmGeneralData } from './agisFarmGeneralData';


export interface AgisGeneralDataType { 
    farmGeneralData?: Array<AgisFarmGeneralData>;
    farmGeneralDataDeclaration?: Array<AgisFarmGeneralDataDeclaration>;
}

