/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisProjectElementsType } from './agisProjectElementsType';


export interface AgisCountrysideQualityProject { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    locality?: string;
    municipalityId?: number;
    projectName: string;
    projectElements: Array<AgisProjectElementsType>;
}

