/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisBiodiversitySurface { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    cultureId?: string;
    locality?: string;
    municipalityId?: number;
    agriculturalZone?: string;
    cultivationType: string;
    cultivationTypeAttribute?: string;
    areaGross?: number;
    areaNet: number;
    biodiversityCategory?: string;
    biodiversityCommitmentStart?: number;
    natureProtectionSurface?: boolean;
    natureProtectionCommitmentStart?: number;
    cultivated?: boolean;
    contributionAuthorization?: boolean;
}

