/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisNetworkContribution { 
    organization: string;
    organizationName?: string;
    federalAmountUsed?: boolean;
    contributionAmount?: number;
}

