/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisSurface { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    cultureId?: string;
    locality?: string;
    municipalityId?: number;
    agriculturalZone?: string;
    cultivationType: string;
    cultivationTypeAttribute?: string;
    areaGross?: number;
    areaNet: number;
    cultivated?: boolean;
    natureProtectionSurface?: boolean;
    psSoilMildTreatment?: boolean;
    psmArableFarming?: boolean;
    psmVegetablesBerries?: boolean;
    psmPerennialCulture?: boolean;
    psmBioAids?: boolean;
    psmHerbicide?: boolean;
    bio?: boolean;
    culturalLandscapeContribution?: boolean;
    individualCultureContribution?: boolean;
}

