/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisSelfReportedDataType { 
    declarationDayQuantity?: number;
    averageQuantity?: number;
    keepingType?: string;
    summeringQuantity?: number;
    summeringDuration?: number;
}

