/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisSlopeSurface { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    cultureId?: string;
    locality?: string;
    municipalityId?: number;
    agriculturalZone?: string;
    cultivationType: string;
    slope18To35Area?: number;
    slope35To50Area?: number;
    slope50PlusArea?: number;
    cultivated?: boolean;
    contributionAuthorization?: boolean;
}

