/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisNetworkSurfaceDataType } from './agisNetworkSurfaceDataType';
import { AgisAnimalDataType } from './agisAnimalDataType';
import { AgisGeneralDataType } from './agisGeneralDataType';
import { AgisBiodiversitySurfaceDataType } from './agisBiodiversitySurfaceDataType';
import { AgisApicultureDataType } from './agisApicultureDataType';
import { AgisAnimalSummeringDataType } from './agisAnimalSummeringDataType';
import { AgisCountrysideQualityDataType } from './agisCountrysideQualityDataType';
import { AgisSlopeSurfaceDataType } from './agisSlopeSurfaceDataType';
import { AgisGrapeSurfaceDataType } from './agisGrapeSurfaceDataType';
import { AgisGeneralSurfaceDataType } from './agisGeneralSurfaceDataType';
import { AgisAquacultureDataType } from './agisAquacultureDataType';


export interface AgisStructuralDataRootType { 
    generalData?: AgisGeneralDataType;
    animalData?: AgisAnimalDataType;
    animalSummeringData?: AgisAnimalSummeringDataType;
    generalSurfaceData?: AgisGeneralSurfaceDataType;
    slopeSurfaceData?: AgisSlopeSurfaceDataType;
    grapeSurfaceData?: AgisGrapeSurfaceDataType;
    biodiversitySurfaceData?: AgisBiodiversitySurfaceDataType;
    networkSurfaceData?: AgisNetworkSurfaceDataType;
    countrysideQualityData?: AgisCountrysideQualityDataType;
    aquacultureData?: AgisAquacultureDataType;
    apicultureData?: AgisApicultureDataType;
}

