/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisAquaticAnimalData } from './agisAquaticAnimalData';


export interface AgisAquacultureDataType { 
    aquaticAnimalData: Array<AgisAquaticAnimalData>;
}

