/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisStructuralDataType } from './agisStructuralDataType';
import { AgisDataRequestTypeType } from './agisDataRequestTypeType';
import { AgisCantonFlAbbreviationType } from './agisCantonFlAbbreviationType';


export interface AgisStructureResponseType { 
    cantonFlAbbreviation: AgisCantonFlAbbreviationType;
    surveyYear: number;
    dataRequestType: AgisDataRequestTypeType;
    structuralData: Array<AgisStructuralDataType>;
}
export namespace AgisStructureResponseType {
}


