/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisSummeringInlandDetails } from './agisSummeringInlandDetails';
import { AgisSummeringAbroadDetails } from './agisSummeringAbroadDetails';
import { AgisSurveyFarmDetails } from './agisSurveyFarmDetails';


export interface AgisAtdDataFinalType { 
    quantityTotal?: number;
    livestockUnitTotal?: number;
    surveyFarmDetails: AgisSurveyFarmDetails;
    summeringInlandDetails?: AgisSummeringInlandDetails;
    summeringAbroadDetails?: AgisSummeringAbroadDetails;
}

