/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisGrapeSurface { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    surfaceId?: string;
    cultureId?: string;
    locality?: string;
    municipalityId?: number;
    agriculturalZone?: string;
    cultivationType: string;
    slopeGrape30To50Area?: number;
    slopeGrape50PlusArea?: number;
    slopeGrapeTerrace?: number;
    bioContribution?: boolean;
    contributionAuthorization?: boolean;
}

