/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisSlopeSurface } from './agisSlopeSurface';


export interface AgisSlopeSurfaceDataType { 
    slopeSurface: Array<AgisSlopeSurface>;
}

