/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisSelfReportedSummeringDataType } from './agisSelfReportedSummeringDataType';
import { AgisAtdSummeringDataType } from './agisAtdSummeringDataType';


export interface AgisAnimalSummeringStock { 
    creationDate?: string;
    animalCategory: string;
    atdData?: AgisAtdSummeringDataType;
    selfreportedData?: Array<AgisSelfReportedSummeringDataType>;
}

