/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgisFarmCharacteristicsType { 
    ZATypology: string;
    surface: number;
    livestockUnit: number;
    structure: boolean;
    summeringStructure: boolean;
    surveyNorm: boolean;
    bioContribution: boolean;
    achieveOeln: boolean;
    directPayment: boolean;
    individualCultureContribution: boolean;
    summeringContribution: boolean;
    insituContribution: boolean;
    cerealsContribution: boolean;
    validSince: string;
}

