/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisCantonFlAbbreviationType } from './agisCantonFlAbbreviationType';


export interface AgisMunicipalityType { 
    municipalityName?: string;
    municipalityId?: number;
    cantonFlAbbreviation?: AgisCantonFlAbbreviationType;
}
export namespace AgisMunicipalityType {
}


