/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisMunicipalityType } from './agisMunicipalityType';


export interface AgisFarmDetailsType { 
    farmType: string;
    localMunicipality?: AgisMunicipalityType;
    coordinatesEast?: number;
    coordinatesNorth?: number;
    altitude?: number;
    agriculturalZone?: string;
    agriculturalArea?: string;
    EGID?: number;
    EGAID?: number;
}

