/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisFarmApicultureData } from './agisFarmApicultureData';


export interface AgisApicultureDataType { 
    farmApicultureData: Array<AgisFarmApicultureData>;
}

