/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisWaterDrainTypes } from './agisWaterDrainTypes';
import { AgisBreedingTypes } from './agisBreedingTypes';
import { AgisProductionForms } from './agisProductionForms';
import { AgisAquaticAnimalTypes } from './agisAquaticAnimalTypes';
import { AgisWaterSupplyTypes } from './agisWaterSupplyTypes';


export interface AgisAquaticAnimalData { 
    creationDate?: string;
    surveyKtIdB: string;
    ber?: string;
    aquaticAnimalTypes?: AgisAquaticAnimalTypes;
    breedingTypes?: AgisBreedingTypes;
    productionForms?: AgisProductionForms;
    waterSupplyTypes?: AgisWaterSupplyTypes;
    waterDrainTypes?: AgisWaterDrainTypes;
}

