/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisAddressInformationType } from './agisAddressInformationType';
import { AgisPersonMailAddressInfoType } from './agisPersonMailAddressInfoType';


export interface AgisPersonMailAddressType { 
    person?: AgisPersonMailAddressInfoType;
    addressInformation?: AgisAddressInformationType;
}

