/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgisPersonMailAddressType } from './agisPersonMailAddressType';
import { AgisMunicipalityType } from './agisMunicipalityType';


export interface AgisPersonDetailsType { 
    legalForm: string;
    dateOfBirth?: string;
    foundationYear?: number;
    languageOfCorrespondance?: string;
    postalAddress?: AgisPersonMailAddressType;
    residenceMunicipality?: AgisMunicipalityType;
    EGAID?: number;
}

