/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FarmTypeEnum } from './farmTypeEnum';


/**
 * Data transfer object representing a bur
 */
export interface BurDto { 
    bur?: string;
    farmTypeCode?: FarmTypeEnum;
}
export namespace BurDto {
}


