/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of the data consumer making the request
 */
export interface ConsentRequestDtoDataRequestDataConsumer { 
    id?: string;
    /**
     * Name of the data consumer organization or individual
     */
    name?: string;
}

