/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestDetailViewDtoDataRequest } from './consentRequestDetailViewDtoDataRequest';
import { ConsentRequestStateEnum } from './consentRequestStateEnum';


/**
 * Data transfer object representing a consent request
 */
export interface ConsentRequestProducerViewDto { 
    id: string;
    /**
     * UID of the data producer
     */
    dataProducerUid?: string;
    /**
     * Current state of the consent request
     */
    stateCode?: ConsentRequestStateEnum;
    /**
     * Date and time when the state was changed last
     */
    lastStateChangeDate?: string;
    requestDate?: string;
    dataRequest?: ConsentRequestDetailViewDtoDataRequest;
}
export namespace ConsentRequestProducerViewDto {
}


