/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestAggregationProducerViewDataRequest } from './consentRequestAggregationProducerViewDataRequest';
import { ConsentRequestAggregationStateEnum } from './consentRequestAggregationStateEnum';
import { ConsentRequestProducerViewDto } from './consentRequestProducerViewDto';


/**
 * Data transfer object representing an aggregation of consent requests
 */
export interface ConsentRequestAggregationProducerView { 
    id: string;
    /**
     * UID of the data producer
     */
    dataProducerUid?: string;
    /**
     * Aggregated state derived from the states of the underlying consent requests
     */
    stateCode?: ConsentRequestAggregationStateEnum;
    /**
     * Indicates whether the aggregated state originates from migrated consent requests
     */
    showStateAsMigrated?: boolean;
    lastStateChangeDate?: string;
    requestDate?: string;
    dataRequest?: ConsentRequestAggregationProducerViewDataRequest;
    consentRequests?: Array<ConsentRequestProducerViewDto>;
}
export namespace ConsentRequestAggregationProducerView {
}


