/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestProducerViewDtoDataRequest } from './consentRequestProducerViewDtoDataRequest';
import { ConsentRequestStateEnum } from './consentRequestStateEnum';


/**
 * Data transfer object representing a consent request
 */
export interface ConsentRequestProducerViewDto { 
    id: string;
    /**
     * UID of the data producer
     */
    dataProducerUid?: string;
    stateCode?: ConsentRequestStateEnum;
    /**
     * Date and time when the state was changed last
     */
    lastStateChangeDate?: string;
    requestDate?: string;
    dataRequest?: ConsentRequestProducerViewDtoDataRequest;
}
export namespace ConsentRequestProducerViewDto {
}


