/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ConsentRequestAggregationStateEnum = {
    Granted: 'GRANTED',
    Opened: 'OPENED',
    Declined: 'DECLINED',
    PartiallyGranted: 'PARTIALLY_GRANTED',
    PartiallyOpened: 'PARTIALLY_OPENED'
} as const;
export type ConsentRequestAggregationStateEnum = typeof ConsentRequestAggregationStateEnum[keyof typeof ConsentRequestAggregationStateEnum];

