/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of the data request
 */
export const ConsentRequestDetailViewDtoDataRequestStateCode = {
    Draft: 'DRAFT',
    Submitted: 'SUBMITTED'
} as const;
export type ConsentRequestDetailViewDtoDataRequestStateCode = typeof ConsentRequestDetailViewDtoDataRequestStateCode[keyof typeof ConsentRequestDetailViewDtoDataRequestStateCode];

