/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StateCountsDto } from './stateCountsDto';


/**
 * KPI summary of consent requests for a data request, broken down by mode (UID/BUR)
 */
export interface ConsentRequestStatusSummaryDto { 
    uid?: StateCountsDto;
    /**
     * Null when the data request has no BUR-based consent requests
     */
    bur?: StateCountsDto;
}

