/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object representing the result of a consent request cleanup run
 */
export interface ConsentRequestCleanupResultDto { 
    fromInclusive?: string;
    toInclusive?: string;
    /**
     * Number of consent requests that were terminated during this run
     */
    terminatedConsentRequestCount?: number;
    /**
     * Duration of the cleanup run in milliseconds
     */
    durationMs?: number;
}

