/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestTitleDto } from './dataRequestTitleDto';


/**
 * Reduced details of the underlying data request
 */
export interface ConsentRequestAggregationSummaryDtoDataRequest { 
    id: string;
    /**
     * Shorter name of the data consumer defined by the data consumer used when displaying the request to the producer
     */
    dataConsumerDisplayName?: string;
    /**
     * Base64-encoded logo of the data consumer
     */
    dataConsumerLogoBase64?: string;
    /**
     * City of the data consumer
     */
    dataConsumerCity?: string;
    /**
     * Title of the data request
     */
    title?: DataRequestTitleDto;
}

