/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object representing a consent request that has been created
 */
export interface ConsentRequestCreatedDto { 
    id: string;
    /**
     * UID of the data producer
     */
    dataProducerUid: string;
    isCreated?: boolean;
}

