/**
 * agridata.ch API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible states of a consent request: - GRANTED: Consent has been granted - OPENED: Consent request is open and awaiting response - DECLINED: Consent has been declined - NOT_CREATED: Placeholder to indicate that no consent request exists yet for a given UID.
 */
export const ConsentRequestStateEnum = {
    Granted: 'GRANTED',
    Opened: 'OPENED',
    Declined: 'DECLINED',
    NotCreated: 'NOT_CREATED'
} as const;
export type ConsentRequestStateEnum = typeof ConsentRequestStateEnum[keyof typeof ConsentRequestStateEnum];

