/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestStateEnum } from './consentRequestStateEnum';


/**
 * Data transfer object representing a consent request
 */
export interface ConsentRequestFundamentalViewDto { 
    id: string;
    dataRequestId: string;
    /**
     * UID of the data producer
     */
    dataProducerUid?: string;
    /**
     * State of the consent request
     */
    stateCode?: ConsentRequestStateEnum;
}
export namespace ConsentRequestFundamentalViewDto {
}


