/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of the data request
 */
export const ConsentRequestProducerViewDtoDataRequestStateCode = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    ToBeSignedByConsumer: 'TO_BE_SIGNED_BY_CONSUMER',
    ToBeReleasedByConsumer: 'TO_BE_RELEASED_BY_CONSUMER',
    ToBeSignedByProvider: 'TO_BE_SIGNED_BY_PROVIDER',
    ToBeReleasedByProvider: 'TO_BE_RELEASED_BY_PROVIDER',
    ToBeActivated: 'TO_BE_ACTIVATED',
    Active: 'ACTIVE'
} as const;
export type ConsentRequestProducerViewDtoDataRequestStateCode = typeof ConsentRequestProducerViewDtoDataRequestStateCode[keyof typeof ConsentRequestProducerViewDtoDataRequestStateCode];

