/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of the data request
 */
export const ConsentRequestDetailViewDtoDataRequestStateCode = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    ToBeSigned: 'TO_BE_SIGNED',
    Active: 'ACTIVE'
} as const;
export type ConsentRequestDetailViewDtoDataRequestStateCode = typeof ConsentRequestDetailViewDtoDataRequestStateCode[keyof typeof ConsentRequestDetailViewDtoDataRequestStateCode];

