/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestStateEnum } from './consentRequestStateEnum';


export interface ConsentRequestAggregationSummaryDtoConsentRequestsInner { 
    id: string;
    /**
     * State of the consent request
     */
    stateCode?: ConsentRequestStateEnum;
}
export namespace ConsentRequestAggregationSummaryDtoConsentRequestsInner {
}


