/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestStateDto } from './consentRequestStateDto';
import { DataRequestSummaryDto } from './dataRequestSummaryDto';
import { ConsentRequestAggregationStateEnum } from './consentRequestAggregationStateEnum';


/**
 * Reduced data transfer object representing an aggregation of consent requests, for list display
 */
export interface ConsentRequestAggregationSummaryDto { 
    id: string;
    /**
     * Aggregated state derived from the states of the underlying consent requests
     */
    stateCode?: ConsentRequestAggregationStateEnum;
    requestDate?: string;
    /**
     * Indicates whether the aggregated state originates from migrated consent requests
     */
    showStateAsMigrated?: boolean;
    lastStateChangeDate?: string;
    /**
     * Reduced details of the underlying data request
     */
    dataRequest?: DataRequestSummaryDto;
    /**
     * List of consent requests included in this aggregation
     */
    consentRequests?: Array<ConsentRequestStateDto>;
}
export namespace ConsentRequestAggregationSummaryDto {
}


