/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestDto } from './dataRequestDto';
import { ConsentRequestAggregationStateEnum } from './consentRequestAggregationStateEnum';
import { ConsentRequestProducerViewV2Dto } from './consentRequestProducerViewV2Dto';


/**
 * Data transfer object representing an aggregation of consent requests
 */
export interface ConsentRequestAggregationDto { 
    id: string;
    /**
     * Aggregated state derived from the states of the underlying consent requests
     */
    stateCode?: ConsentRequestAggregationStateEnum;
    requestDate?: string;
    /**
     * Indicates whether the aggregated state originates from migrated consent requests
     */
    showStateAsMigrated?: boolean;
    lastStateChangeDate?: string;
    /**
     * Details of the underlying data request
     */
    dataRequest?: DataRequestDto;
    /**
     * List of consent requests included in this aggregation
     */
    consentRequests?: Array<ConsentRequestProducerViewV2Dto>;
}
export namespace ConsentRequestAggregationDto {
}


