/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestAggregationProducerViewDataRequest } from './consentRequestAggregationProducerViewDataRequest';
import { ConsentRequestStateEnum } from './consentRequestStateEnum';


/**
 * Data transfer object representing a consent request
 */
export interface ConsentRequestProducerViewDto { 
    id: string;
    /**
     * UID of the data producer
     */
    dataProducerUid?: string;
    /**
     * BUR of the data producer; null for UID-based consent requests
     */
    dataProducerBur?: string;
    stateCode?: ConsentRequestStateEnum;
    /**
     * If the state should be shown as migrated
     */
    showStateAsMigrated?: boolean;
    /**
     * Date and time when the state was changed last
     */
    lastStateChangeDate?: string;
    requestDate?: string;
    dataRequest?: ConsentRequestAggregationProducerViewDataRequest;
}
export namespace ConsentRequestProducerViewDto {
}


