/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentRequestDtoDataRequestDataConsumer } from './consentRequestDtoDataRequestDataConsumer';
import { TranslationDto } from './translationDto';


/**
 * Details of the underlying data request
 */
export interface ConsentRequestDtoDataRequest { 
    id: string;
    /**
     * Title of the data request
     */
    title?: TranslationDto;
    /**
     * Description of the data request 
     */
    description?: TranslationDto;
    /**
     * Purpose of the data request
     */
    purpose?: TranslationDto;
    dataConsumer?: ConsentRequestDtoDataRequestDataConsumer;
}

