/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignatureSlotCodeEnum } from './signatureSlotCodeEnum';


export interface ContractRevisionSignatureDto { 
    /**
     * Slot in which the signature is stored
     */
    signatureSlotCode: SignatureSlotCodeEnum;
    userId: string;
    /**
     * Name of the user of the signature
     */
    name: string;
    timestamp: string;
}
export namespace ContractRevisionSignatureDto {
}


