/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractRevisionSignatureDto } from './contractRevisionSignatureDto';
import { DataRequestContextDto } from './dataRequestContextDto';
import { SignatureTypeEnum } from './signatureTypeEnum';


export interface ContractRevisionDto { 
    id: string;
    dataRequestId: string;
    /**
     * LegalName of the data consumer taken from the uid register
     */
    dataConsumerName: string;
    /**
     * City of the data consumer
     */
    dataConsumerCity: string;
    /**
     * Name of the data provider
     */
    dataProviderName: string;
    /**
     * City of the data provider
     */
    dataProviderCity: string;
    /**
     * Contextual information from the parent data request (e.g. logo, reduced metadata)
     */
    dataRequestContext: DataRequestContextDto;
    /**
     * List of signatures of the data consumer
     */
    consumerSignatures?: Array<ContractRevisionSignatureDto>;
    /**
     * List of signatures of the data provider
     */
    providerSignatures?: Array<ContractRevisionSignatureDto>;
    /**
     * Defines whether the consumer party uses a individual or a collective signature
     */
    consumerSignatureType?: SignatureTypeEnum;
    /**
     * Defines whether the provider party uses a individual or a collective signature
     */
    providerSignatureType?: SignatureTypeEnum;
}
export namespace ContractRevisionDto {
}


