/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object used to create consent requests for a data producer UID and optionally its BURs
 */
export interface CreateConsentRequestsForUidDto { 
    /**
     * UID of the data producer
     */
    uid: string;
    /**
     * BURs of the data producer. Required, but may be empty. Every BUR must belong to the UID in AGIS.
     */
    burs: Array<string>;
}

