/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DataRequestStateEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    ToBeSignedByConsumer: 'TO_BE_SIGNED_BY_CONSUMER',
    ToBeReleasedByConsumer: 'TO_BE_RELEASED_BY_CONSUMER',
    ToBeSignedByProvider: 'TO_BE_SIGNED_BY_PROVIDER',
    Active: 'ACTIVE'
} as const;
export type DataRequestStateEnum = typeof DataRequestStateEnum[keyof typeof DataRequestStateEnum];

