/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranslationDto } from './translationDto';


export interface DataProviderReferenceDto { 
    id?: string;
    /**
     * Stable technical code of the provider
     */
    code?: string;
    /**
     * Display name of the provider
     */
    name?: TranslationDto;
    /**
     * UID of the data provider
     */
    uid?: string;
}

