/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestPurposeDto } from './dataRequestPurposeDto';
import { DataRequestTitleDto } from './dataRequestTitleDto';
import { ConsentRequestDetailViewDtoDataRequestStateCode } from './consentRequestDetailViewDtoDataRequestStateCode';
import { DataRequestDescriptionDto } from './dataRequestDescriptionDto';


/**
 * Details of the underlying data request
 */
export interface DataRequestDto { 
    id?: string;
    /**
     * Human friendly id of the data request
     */
    humanFriendlyId?: string;
    /**
     * Date and time when the data request was submitted
     */
    submissionDate?: string;
    /**
     * Title of the data request
     */
    title?: DataRequestTitleDto;
    /**
     * Description of the data request 
     */
    description?: DataRequestDescriptionDto;
    /**
     * Purpose of the data request
     */
    purpose?: DataRequestPurposeDto;
    /**
     * List of data products requested
     */
    products?: Array<string>;
    stateCode: ConsentRequestDetailViewDtoDataRequestStateCode;
    /**
     * LegalName of the data consumer taken from the uid register
     */
    dataConsumerLegalName?: string;
    /**
     * Shorter name of the data consumer defined by the data consumer used when displaying the request to the producer
     */
    dataConsumerDisplayName?: string;
    /**
     * Uid of the data consumer
     */
    dataConsumerUid?: number;
    /**
     * City of the data consumer
     */
    dataConsumerCity?: string;
    /**
     * Zip code of the data consumer
     */
    dataConsumerZip?: string;
    /**
     * Street of the data consumer
     */
    dataConsumerStreet?: string;
    /**
     * 2 letter country code of the data consumer
     */
    dataConsumerCountry?: string;
    /**
     * Contact phone number for the data request
     */
    contactPhoneNumber?: string;
    /**
     * Contact email address for the data request
     */
    contactEmailAddress?: string;
    /**
     * Base64-encoded logo of the data consumer
     */
    dataConsumerLogoBase64?: string;
}
export namespace DataRequestDto {
}


