/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestPurposeDto } from './dataRequestPurposeDto';
import { DataRequestTitleDto } from './dataRequestTitleDto';
import { DataRequestDescriptionDto } from './dataRequestDescriptionDto';


/**
 * Data transfer object representing a data request
 */
export interface DataRequestUpdateDto { 
    /**
     * Title of the data request
     */
    title?: DataRequestTitleDto;
    /**
     * Description of the data request 
     */
    description?: DataRequestDescriptionDto;
    /**
     * Purpose of the data request
     */
    purpose?: DataRequestPurposeDto;
    /**
     * Shorter name of the data consumer defined by the data consumer used when displaying the request to the producer
     */
    dataConsumerDisplayName?: string;
    /**
     * City of the data consumer
     */
    dataConsumerCity?: string;
    /**
     * Zip code of the data consumer
     */
    dataConsumerZip?: string;
    /**
     * Street of the data consumer
     */
    dataConsumerStreet?: string;
    /**
     * 2 letter country code of the data consumer
     */
    dataConsumerCountry?: string;
    /**
     * List of data products requested
     */
    products?: Array<string>;
}

