/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataProviderReferenceDto } from './dataProviderReferenceDto';
import { TranslationDto } from './translationDto';


export interface DataSourceSystemReferenceDto { 
    id?: string;
    code?: string;
    name?: TranslationDto;
    dataProvider: DataProviderReferenceDto;
}

