/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowCodeEnum } from './flowCodeEnum';
import { RestClientMethodCodeEnum } from './restClientMethodCodeEnum';
import { DataProductNameDto } from './dataProductNameDto';
import { DataProductDescriptionDto } from './dataProductDescriptionDto';


/**
 * Data transfer object representing a data product
 */
export interface DataProductUpdateDto { 
    /**
     * Name of the data product
     */
    name?: DataProductNameDto;
    /**
     * Description of the data product
     */
    description?: DataProductDescriptionDto;
    dataSourceSystemId: string;
    restClientId?: string;
    /**
     * Template for the path from which the data product will be fetched
     */
    restClientPathTemplate?: string;
    /**
     * Template for the path from which the data product will be fetched
     */
    restClientRequestTemplate?: string;
    /**
     * The http-method used to fetch the data product
     */
    restClientMethodCode?: RestClientMethodCodeEnum;
    /**
     * The flow code used for authorizing data retrieval
     */
    flowCode?: FlowCodeEnum;
    /**
     * Template for the path for retrieving updates to the data product
     */
    restClientChangeDetectionPathTemplate?: string;
}
export namespace DataProductUpdateDto {
}


