/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing the requested product data and metadata about the request.
 */
export interface DataTransferResponse { 
    data?: any | null;
    /**
     * Unique identifier for the data transfer request (uuid)
     */
    dataTransferRequestId?: string;
    consentRequestId?: string;
}

