/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestPurposeDto } from './dataRequestPurposeDto';
import { DataRequestTitleDto } from './dataRequestTitleDto';
import { DataRequestDescriptionDto } from './dataRequestDescriptionDto';


/**
 * Data transfer object representing a data request
 */
export interface DataRequestUpdateDto { 
    /**
     * Title of the data request
     */
    title?: DataRequestTitleDto;
    /**
     * Description of the data request 
     */
    description?: DataRequestDescriptionDto;
    /**
     * Purpose of the data request
     */
    purpose?: DataRequestPurposeDto;
    /**
     * List of data products requested
     */
    products?: Array<string>;
}

