/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceSystemEnum } from './dataSourceSystemEnum';
import { TranslationDto } from './translationDto';


export interface DataProductDto { 
    id: string;
    /**
     * From which data source system this product originates
     */
    dataSourceSystemCode?: DataSourceSystemEnum;
    /**
     * How this product is categorized
     */
    name?: TranslationDto;
    /**
     * Description of the product
     */
    description?: TranslationDto;
    /**
     * The identifier of the product in the data source system
     */
    dataSourceProductId: string;
}
export namespace DataProductDto {
}


