/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataProviderReferenceDto } from './dataProviderReferenceDto';
import { TranslationDto } from './translationDto';


export interface DataSourceSystemReferenceDto { 
    id?: string;
    /**
     * Stable technical code of the source
     */
    code?: string;
    /**
     * Display name of the data source
     */
    name?: TranslationDto;
    /**
     * Reference to the data provider
     */
    dataProvider: DataProviderReferenceDto;
}

