/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthStatus } from './healthStatus';
import { TranslationDto } from './translationDto';


/**
 * Health status of a single data source system
 */
export interface DataProviderStatus { 
    /**
     * Name of the data provider operating the system
     */
    providerName?: TranslationDto;
    /**
     * Name of the data source system
     */
    systemName?: TranslationDto;
    /**
     * Current health of the data source system
     */
    status?: HealthStatus;
}
export namespace DataProviderStatus {
}


