/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowCodeEnum } from './flowCodeEnum';
import { RestClientMethodCodeEnum } from './restClientMethodCodeEnum';
import { LinkDto } from './linkDto';
import { DataProductExtendedDescriptionDto } from './dataProductExtendedDescriptionDto';
import { DataProductNameDto } from './dataProductNameDto';
import { DataProductDescriptionDto } from './dataProductDescriptionDto';


/**
 * Data transfer object representing a data product
 */
export interface DataProductUpdateDto { 
    name?: DataProductNameDto;
    description?: DataProductDescriptionDto;
    dataSourceSystemId?: string;
    restClientId?: string;
    restClientPathTemplate?: string;
    restClientRequestTemplate?: string;
    restClientMethodCode?: RestClientMethodCodeEnum;
    flowCode?: FlowCodeEnum;
    restClientChangeDetectionPathTemplate?: string;
    links?: Array<LinkDto>;
    extendedDescription?: DataProductExtendedDescriptionDto;
    consentRequired?: boolean;
    paymentRequired?: boolean;
    pricingBasis?: DataProductDescriptionDto;
    pricingBasisPresentWhenPaymentRequired?: boolean;
    pricingBasisAbsentWhenPaymentNotRequired?: boolean;
}
export namespace DataProductUpdateDto {
}


