/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data transfer object representing a minimal version of a data request for UI/UX use.
 */
export interface DataRequestContextDto { 
    /**
     * Base64-encoded logo of the data consumer
     */
    dataConsumerLogoBase64?: string;
}

