/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataRequestDescriptionDto { 
    /**
     * Description of the data request
     */
    de?: string;
    /**
     * Description de la demande de données
     */
    fr?: string;
    /**
     * Descrizione della richiesta di dati
     */
    it?: string;
}

