/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceSystemDto } from './dataSourceSystemDto';
import { TranslationDto } from './translationDto';


export interface DataProductV2Dto { 
    id: string;
    /**
     * Code of data source system from which this product originates
     */
    dataSourceSystemCode?: string;
    /**
     * Code of data source system from which this product originates
     */
    dataSourceSystem?: DataSourceSystemDto;
    /**
     * How this product is categorized
     */
    name?: TranslationDto;
    /**
     * Description of the product
     */
    description?: TranslationDto;
}

