/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestPurposeDto } from './dataRequestPurposeDto';
import { ConsentRequestDtoDataRequestDataConsumer } from './consentRequestDtoDataRequestDataConsumer';
import { DataRequestTitleDto } from './dataRequestTitleDto';
import { ConsentRequestDtoDataRequestStateCode } from './consentRequestDtoDataRequestStateCode';
import { DataRequestDescriptionDto } from './dataRequestDescriptionDto';
import { ConsentRequestDtoDataRequestProducts } from './consentRequestDtoDataRequestProducts';


/**
 * Details of the underlying data request
 */
export interface DataRequestDto { 
    id?: string;
    /**
     * Title of the data request
     */
    title?: DataRequestTitleDto;
    /**
     * Description of the data request 
     */
    description?: DataRequestDescriptionDto;
    /**
     * Purpose of the data request
     */
    purpose?: DataRequestPurposeDto;
    dataConsumer?: ConsentRequestDtoDataRequestDataConsumer;
    products?: ConsentRequestDtoDataRequestProducts;
    stateCode: ConsentRequestDtoDataRequestStateCode;
}
export namespace DataRequestDto {
}


