/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataRequestValidRedirectUriRegexUpdateDto { 
    /**
     * Regex used to validate redirect_uri values for this data request. Must compile as regex successfully.
     */
    validRedirectUriRegex?: string;
}

