/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataProviderDto } from './dataProviderDto';
import { TranslationDto } from './translationDto';


export interface DataSourceSystemDto { 
    id: string;
    code?: string;
    name?: TranslationDto;
    dataProvider: DataProviderDto;
}

