/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataProductNameDto { 
    /**
     * German name of the data product
     */
    de?: string;
    /**
     * French name of the data product
     */
    fr?: string;
    /**
     * Italian name of the data product
     */
    it?: string;
}

