/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExceptionEnum } from './exceptionEnum';


export interface DataProviderExceptionDto { 
    message?: string;
    requestId?: string;
    exceptionType?: ExceptionEnum;
    dataProviderHttpStatus?: number;
    dataProviderMessage?: string;
}
export namespace DataProviderExceptionDto {
}


