/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DataSourceSystemEnum = {
    Agis: 'AGIS'
} as const;
export type DataSourceSystemEnum = typeof DataSourceSystemEnum[keyof typeof DataSourceSystemEnum];

