/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataProductTechnicalDescriptionDto { 
    /**
     * German technical description of the data product
     */
    de?: string;
    /**
     * French technical description of the data product
     */
    fr?: string;
    /**
     * Italian technical description of the data product
     */
    it?: string;
}

