/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentScanStatusEnum } from './documentScanStatusEnum';


export interface DataProductDocumentMetadataDto { 
    id: string;
    /**
     * Filename of the document
     */
    fileName: string;
    /**
     * Filesize of the document
     */
    sizeBytes: number;
    /**
     * Status of the document scan
     */
    scanStatus: DocumentScanStatusEnum;
}
export namespace DataProductDocumentMetadataDto {
}


