/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentScanStatus } from './documentScanStatus';


export interface DataProductDocumentMetadataDto { 
    id?: string;
    fileName?: string;
    sizeBytes?: number;
    scanStatus?: DocumentScanStatus;
}
export namespace DataProductDocumentMetadataDto {
}


