/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceSystemDto } from './dataSourceSystemDto';
import { FlowCodeEnum } from './flowCodeEnum';
import { RestClientMethodCodeEnum } from './restClientMethodCodeEnum';
import { LinkDto } from './linkDto';
import { RestClientDto } from './restClientDto';
import { DataProductDtoStateCode } from './dataProductDtoStateCode';
import { TranslationDto } from './translationDto';


export interface DataProductDto { 
    id: string;
    /**
     * Code of data source system from which this product originates
     */
    dataSourceSystemCode?: string;
    /**
     * Data source system from which this product originates
     */
    dataSourceSystem?: DataSourceSystemDto;
    /**
     * Rest client used to fetch the data product
     */
    restClient?: RestClientDto;
    /**
     * Template for the path where the data product is fetched from
     */
    restClientPathTemplate?: string;
    /**
     * Template of the request body for fetching the data product
     */
    restClientRequestTemplate?: string;
    /**
     * Http-Method used to fetch the data product
     */
    restClientMethodCode?: RestClientMethodCodeEnum;
    /**
     * Code of the flow used to fetch the data product
     */
    flowCode?: FlowCodeEnum;
    /**
     * How this product is categorized
     */
    name?: TranslationDto;
    /**
     * Description of the product
     */
    description?: TranslationDto;
    /**
     * List of relevant product links
     */
    links?: Array<LinkDto>;
    /**
     * Technical product details
     */
    technicalDescription?: TranslationDto;
    deprecatedSince?: string;
    stateCode: DataProductDtoStateCode;
    /**
     * Template for the path for retrieving updates to the data product
     */
    restClientChangeDetectionPathTemplate?: string;
}
export namespace DataProductDto {
}


