/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ExceptionEnum = {
    Generic: 'GENERIC',
    UidMissing: 'UID_MISSING',
    ExternalServiceError: 'EXTERNAL_SERVICE_ERROR',
    ConsentNotGranted: 'CONSENT_NOT_GRANTED',
    OtpInvalid: 'OTP_INVALID',
    OtpLocked: 'OTP_LOCKED',
    OtpExpired: 'OTP_EXPIRED',
    OtpResendCooldown: 'OTP_RESEND_COOLDOWN',
    DataProviderError: 'DATA_PROVIDER_ERROR',
    Maintenance: 'MAINTENANCE'
} as const;
export type ExceptionEnum = typeof ExceptionEnum[keyof typeof ExceptionEnum];

