/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ExceptionEnum = {
    Generic: 'GENERIC',
    UidMissing: 'UID_MISSING',
    ExternalServiceError: 'EXTERNAL_SERVICE_ERROR'
} as const;
export type ExceptionEnum = typeof ExceptionEnum[keyof typeof ExceptionEnum];

