/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FarmTypeEnum = {
    Ganzjahresbetrieb: 'GANZJAHRESBETRIEB',
    Produktionsstaette: 'PRODUKTIONSSTAETTE',
    Gemeinschaftsweidebetrieb: 'GEMEINSCHAFTSWEIDEBETRIEB',
    Soemmerungsbetrieb: 'SOEMMERUNGSBETRIEB',
    Betriebsgemeinschaft: 'BETRIEBSGEMEINSCHAFT',
    Viehhandesunternehmen: 'VIEHHANDESUNTERNEHMEN',
    Wanderherde: 'WANDERHERDE',
    Tierklinik: 'TIERKLINIK',
    Schlachtbetrieb: 'SCHLACHTBETRIEB',
    ViehmaerkteUndVeranstaltungen: 'VIEHMAERKTE_UND_VERANSTALTUNGEN',
    Betriebszweiggemeinschaft: 'BETRIEBSZWEIGGEMEINSCHAFT',
    NichtkommerzielleTierhaltung: 'NICHTKOMMERZIELLE_TIERHALTUNG',
    OelnGemeinschaft: 'OELN_GEMEINSCHAFT',
    VergaerungKompostierungNaehrstoffpool: 'VERGAERUNG_KOMPOSTIERUNG_NAEHRSTOFFPOOL',
    Tierhaltung: 'TIERHALTUNG',
    NichtZugeteilt: 'NICHT_ZUGETEILT',
    Unknown: 'UNKNOWN'
} as const;
export type FarmTypeEnum = typeof FarmTypeEnum[keyof typeof FarmTypeEnum];

