/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FlowCodeEnum = {
    UidBasedPreValidation: 'UID_BASED_PRE_VALIDATION',
    UidBasedPostValidation: 'UID_BASED_POST_VALIDATION',
    BurBasedPreValidation: 'BUR_BASED_PRE_VALIDATION',
    BurBasedPostValidation: 'BUR_BASED_POST_VALIDATION',
    UnboundPostValidation: 'UNBOUND_POST_VALIDATION'
} as const;
export type FlowCodeEnum = typeof FlowCodeEnum[keyof typeof FlowCodeEnum];

