/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Health status. HEALTH_CHECK_NOT_IMPLEMENTED marks systems without a health probe
 */
export const HealthStatus = {
    Up: 'UP',
    Down: 'DOWN',
    HealthCheckNotImplemented: 'HEALTH_CHECK_NOT_IMPLEMENTED'
} as const;
export type HealthStatus = typeof HealthStatus[keyof typeof HealthStatus];

