/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataProviderStatus } from './dataProviderStatus';
import { HealthStatus } from './healthStatus';


/**
 * Public health status of agridata.ch and its connected data source systems
 */
export interface HealthDto { 
    /**
     * Overall readiness of agridata.ch itself. Not affected by the data provider statuses
     */
    agridataStatus?: HealthStatus;
    /**
     * Per data source system health summary
     */
    dataProviders?: Array<DataProviderStatus>;
}
export namespace HealthDto {
}


