/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetTypeCodeEnum } from './targetTypeCodeEnum';
import { TranslationDto } from './translationDto';


export interface InboxEntryDto { 
    id?: string;
    title?: TranslationDto;
    text?: TranslationDto;
    userId?: string;
    isRead?: boolean;
    createdAt?: string;
    targetType?: TargetTypeCodeEnum;
    targetId?: string;
}
export namespace InboxEntryDto {
}


