/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LegalFormEnum = {
    NatuerlichePerson: 'NATUERLICHE_PERSON',
    EinfacheGesellschaft: 'EINFACHE_GESELLSCHAFT',
    Kollektivgesellschaft: 'KOLLEKTIVGESELLSCHAFT',
    Kommanditgesellschaft: 'KOMMANDITGESELLSCHAFT',
    Kommanditaktiengesellschaft: 'KOMMANDITAKTIENGESELLSCHAFT',
    Aktiengesellschaft: 'AKTIENGESELLSCHAFT',
    Gmbh: 'GMBH',
    Genossenschaft: 'GENOSSENSCHAFT',
    Verein: 'VEREIN',
    Stiftung: 'STIFTUNG',
    OeffRechtKoerperschaftVerwaltung: 'OEFF_RECHT_KOERPERSCHAFT_VERWALTUNG',
    Landeskirche: 'LANDESKIRCHE',
    Bund: 'BUND',
    Kanton: 'KANTON',
    Bezirk: 'BEZIRK',
    Gemeinde: 'GEMEINDE',
    OeffRechtKoerperschaftBetrieb: 'OEFF_RECHT_KOERPERSCHAFT_BETRIEB',
    Unknown: 'UNKNOWN'
} as const;
export type LegalFormEnum = typeof LegalFormEnum[keyof typeof LegalFormEnum];

