/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OtpChallengeDto { 
    challengeId?: string;
    expiresAt?: string;
    /**
     * Masked phone number
     */
    maskedPhoneNumber?: string;
    /**
     * Number of remaining attempts
     */
    retryAfterSeconds?: number;
}

