/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './userInfoDto';


export interface PageResponseDtoUserInfoDto { 
    items?: Array<UserInfoDto>;
    totalItems?: number;
    totalPages?: number;
    currentPage?: number;
    pageSize?: number;
}

