/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Generic paginated response wrapper.
 */
export interface PageResponseDto { 
    /**
     * List of items on the current page.
     */
    items: Array<any>;
    /**
     * Total number of items across all pages.
     */
    totalItems: number;
    /**
     * Total number of pages available.
     */
    totalPages: number;
    /**
     * Current page number (0-based ).
     */
    currentPage: number;
    /**
     * Number of items per page.
     */
    pageSize: number;
}

