/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProducerIdentifier { 
    /**
     * Producer UID
     */
    uid?: string;
    /**
     * Producer BUR, only set when the producer must additionally be identified by BUR.
     */
    bur?: string | null;
}

