/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceSystemDto } from './dataSourceSystemDto';
import { FlowCodeEnum } from './flowCodeEnum';
import { LinkDto } from './linkDto';
import { DataProductDtoStateCode } from './dataProductDtoStateCode';
import { TranslationDto } from './translationDto';


export interface PublicDataProductDto { 
    id: string;
    /**
     * Data source system from which this product originates
     */
    dataSourceSystem?: DataSourceSystemDto;
    /**
     * Code of the flow used to fetch the data product
     */
    flowCode?: FlowCodeEnum;
    /**
     * Localized name of the product
     */
    name?: TranslationDto;
    /**
     * Description of the product
     */
    description?: TranslationDto;
    /**
     * List of relevant product links
     */
    links?: Array<LinkDto>;
    /**
     * Extended product details
     */
    extendedDescription?: TranslationDto;
    deprecatedSince?: string;
    stateCode: DataProductDtoStateCode;
}
export namespace PublicDataProductDto {
}


