/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceQueryDto { 
    /**
     * page number
     */
    page?: number;
    /**
     * page size
     */
    size?: number;
    /**
     * List of field names to sort by. Default is ascending prefix with - for descending
     */
    sortParams?: Array<string>;
    /**
     * string to search for in the resource
     */
    searchTerm?: string;
    /**
     * Column filters in the form \'<column>:<value>[,<value>]\', multiple filters separated by \';\'. Values of the same column are combined with OR, filters on different columns with AND. Duplicate values are ignored. The filterable columns are documented per endpoint.
     */
    columnFilters?: Array<string>;
    /**
     * language code for multilingual fields. Must be supported by application.
     */
    language?: string;
}

