/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceQueryDto { 
    /**
     * page number
     */
    page?: number;
    /**
     * page size
     */
    size?: number;
    /**
     * List of field names to sort by. Default is ascending prefix with - for descending
     */
    sortParams?: Array<string>;
    /**
     * string to search for in the resource
     */
    searchTerm?: string;
}

