/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Counts of consent requests by status, for a single mode (UID or BUR)
 */
export interface StateCountsDto { 
    total?: number;
    open?: number;
    granted?: number;
    declined?: number;
}

