/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegalFormEnum } from './legalFormEnum';


/**
 * Data transfer object representing an uid
 */
export interface UidDto { 
    uid?: string;
    name?: string;
    legalFormCode?: LegalFormEnum;
}
export namespace UidDto {
}


