/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UidRegisterAddressDto } from './uidRegisterAddressDto';


export interface UidRegisterOrganisationDto { 
    name?: string;
    legalName?: string;
    uid?: number;
    address?: UidRegisterAddressDto;
}

