/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents basic user information, such as name, contact details, and address.
 */
export interface UserInfoDto { 
    /**
     * KtIdP of the user. Only set for data producers
     */
    ktIdP?: string;
    /**
     * UID of the user. Only set for data consumers.
     */
    uid?: string;
    /**
     * User\'s first name.
     */
    givenName?: string;
    /**
     * User\'s last name.
     */
    familyName?: string;
    /**
     * Email address of the user
     */
    email?: string;
    /**
     * Phone number of the user
     */
    phoneNumber?: string;
    /**
     * Street name and house number of the user\'s residence.
     */
    addressStreet?: string;
    /**
     * Locality (city or town) of the user\'s residence.
     */
    addressLocality?: string;
    /**
     * Postal code of the user\'s residence.
     */
    addressPostalCode?: string;
    /**
     * Country of residence
     */
    addressCountry?: string;
    lastLoginDate?: string;
}

