/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPreferencesDto { 
    /**
     * If the main menu is opened or closed.
     */
    mainMenuOpened?: boolean;
    /**
     * the active uid of the producer
     */
    activeUid?: string;
    /**
     * consent request ids for which we dont want to show migration notices anymore
     */
    dismissedMigratedIds?: Array<string>;
}

