/**
 * agridata.ch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VerifyOtpRequestDto { 
    /**
     * The 6-digit code to be verified.
     */
    otpCode: string;
}

